---
title: "R Notebook"
output: html_notebook
---

# Load packages and answer key
```{r}
#library(here)
library(tidyverse)   # include stringr
#library(tabulizer)

course_code = "FR2203"
pdf_answerkey <- file.path("D:\\OneDrive - City, University of London\\@Courses\\FR2203\\! Exam, test, tutorials",
                           "FR2203 (updated) - Online Company Valuation Answers - May 2020.pdf")

data_answerkey <- pdftools::pdf_data(pdf_answerkey)[[1]] %>% 
  filter(y > 181 & y < 680) %>% 
  filter(x >= 99 & x <= 156) %>% 
  select(-c(width, height, space)) %>% 
  group_by(y) %>% 
  spread(key = x, value = text) %>% 
  ungroup() %>% 
  mutate(Question = `142`, Answer = coalesce(`150`, `156`)) %>% 
  select(Question, Answer) 

#for tm::, see also https://www.charlesbordet.com/en/extract-pdf/#use-pdftoolspdf_text

```

# Process pdf MC answer sheet
```{r, message=F}

script_dir = "allScripts" #"wrongScripts - Copy"
pdf_path = "D:\\OneDrive - City, University of London\\@Courses\\FR2203\\! Xchg"
#pdf_path = "D:\\OneDrive - City, University of London\\@Courses\\FR2203\\! Xchg\\allScripts"
files <- list.files(path = file.path(pdf_path, script_dir))
#keep only pdf files
files <- files[grepl(".pdf", files)]

#-----------------------------------------2bdel write

df.MC <- data.frame()
#loop through all pdf files
for(i in 1:length(files)){  #length(files)
  
#i=1
  pdf_file <- file.path(pdf_path, script_dir, files[i])
  
  
  studentID <- (files[i] %>% stringr::str_split(pattern = "( |\\p{P})", n = 2, simplify = T) %>% 
                     c())[1]  
    
  data_prelim <- data.frame()
  for (j in ifelse(studentID == "180003772" | studentID == "180026374", 3, 2):3) {  

#j=2    
    data_temp <- pdftools::pdf_data(pdf_file)[[j]] %>% 
      
    # pdf_file <- file.path(pdf_path, script_dir, "180003772.FR2203.pdf")
    # data_prelim <- pdftools::pdf_data(pdf_file)[[3]] %>% 
      
      # take care of a weird case where extra ! appear next to numbers and alphabets
      mutate(text = str_replace_all(text, " |!|\\)", "") %>% str_squish()) %>% 
      filter(text != "") %>% 
      # remove rows for page number
      filter(y < 778) %>% 
      mutate(y = j + y/max(y)) %>% 
      arrange(y) 
      # filter(y > 184 & y < 613) %>% 
      # filter(x < 206) %>% 
      # extract only rows containing question no. 1-20 and the MC ans
    
    data_prelim <- bind_rows(data_prelim, data_temp) %>% 
        slice(min(which(.$text == 1)):          
              # max(which(.$text == 20))) %>%   # extract only rows containing question no. 1-20 and the MC ans
              max(which(.$text == 
                      min(21, # extract only rows containing question no. 1-21 and the MC ans in-between
                          filter(., grepl("^[0-9]{1,2}$", text))$text %>%
                            as.numeric() %>% 
                            max(na.rm = T))
                      ))
              # allow for truncated tables with, say, only up to Q17
              # handled by finding the max Q no. and capped it at 20 (to avoid wrongly including Q21, etc)
            ) %>% 
#      filter(text != "21")
#      filter(grepl("^([0-9]|1[0-9]|20|[A-Za-z])$", text))
      filter(grepl("^([0-9]|1[0-9]|20|21|[A-Za-z])$", text))
      
    if (nrow(data_prelim) == 62) break
#    if (nrow(data_prelim) == 60) break
    
    } #end of inner for-loop

      
  #suppressWarnings({    
  data_MCanswers <- data_prelim %>%     
    # slice(min(which(.$text == 1)):          
    #         # max(which(.$text == 20))) %>%   # extract only rows containing question no. 1-20 and the MC ans
    #         max(which(.$text == 
    #                 min(20, # extract only rows containing question no. 1-21 and the MC ans in-between
    #                     filter(., grepl("^[0-9]{1,2}$", text))$text %>%
    #                       as.numeric() %>% 
    #                       max(na.rm = T))
    #                 ))
    #         # allow for truncated tables with, say, only up to Q17
    #         # handled by finding the max Q no. and capped it at 20 (to avoid wrongly including Q21, etc)
    #       ) %>%   
    select(-c(width, height, space)) %>% 
    group_by(y) %>% 
    spread(key = x, value = text) %>% 
    ungroup() %>% 
  #    select(-y) %>% 
    hablar::retype()  # change the type of each column accordingly
  #})
  
        
  # separate numeric and non-numeric columns    
  num_data <- select_if(data_MCanswers, is.numeric) %>% select(-y)
  nonnum_data <- select_if(data_MCanswers, negate(is.numeric))
  
  # consolidate numeric and non-numeric columns into Question and Answer columns
  answers_prelim <- data_MCanswers %>% 
    mutate(Question = do.call(coalesce, num_data), 
           Answer = do.call(coalesce, nonnum_data) %>% toupper(),
           ) %>% 
    select(y, Question, Answer) %>% 
    mutate(y_L1 = lag(y),
           y_F1 = lead(y),
           ) %>% 
    select(y, y_F1, y_L1, everything()) %>% 
    # replace missing Question no. by closest non-missing value
    mutate(Question = #Question_my = 
             ifelse( is.na(Question) & is.na(y_F1) & is.na(y_L1), Question, 
             ifelse( is.na(Question) & !is.na(y_F1) & is.na(y_L1), lead(Question), 
             ifelse( is.na(Question) & is.na(y_F1) & !is.na(y_L1), lag(Question), 
             ifelse( is.na(Question) & (abs(y_F1 - y) <= abs(y_L1 - y)), lead(Question), 
             ifelse( is.na(Question) & (abs(y_F1 - y) > abs(y_L1 - y)), lag(Question), 
               Question
               ))))) 
           ) %>% 
    # remove missing Answer
    filter(!is.na(Answer))
     
  
  answers_long <- answers_prelim %>%     
  #  filter(Question <= 20) %>% 
    select(Question, Answer) %>% 
    # NOte: very important to sort here (for answer table that spread between p. 2 and p. 3)
    arrange(Question)

  
#####################################################
  if (nrow(answers_long) != 20) { 
    cat("\n---------------> ", i, ": wrong table! - ", files[i], "\n")
    file.copy(file.path(pdf_path, script_dir, files[i]), file.path(pdf_path, "wrongScripts", files[i]), 
              overwrite = TRUE)
    } else {
   
    # Mark correct answers based on data_answerkey
    answers_marked <- answers_long %>%  #data_MCanswers %>%      
      mutate(Correct = ifelse(Answer == data_answerkey$Answer, 1, 0)) %>% 
      add_row(Question = 0, 
              Correct = sum( (.) %>% filter(Question >= 1 & Question <= 20) %>% select(Correct)),
              # Note: sum() and !is.na() are functions that do not take dataframe as an input and thus cannot follow %>%)
              Answer = #paste(Correct,
                sum(!is.na( (.) %>% filter(Question >= 1 & Question <= 20) %>% select(Answer))),
                              # sep = "."),
              ) %>% 
      arrange(Question) 
    
    
    # flip from long to wide
    answers_wide <- answers_marked %>% 
      gather(key = "type", value = "value", 2:3) %>% 
      spread(key = Question, value = value,
             sep = "_") %>% 
      rename(count = Question_0) %>% 
      mutate(count = as.integer(count)) %>% 
      mutate(student = studentID) %>% 
      # mutate(student = (files[i] %>% 
      #                stringr::str_split(pattern = "(\\p{P})", n = 2, simplify = T) %>% 
      #                c())[1]
      #        ) %>% 
      select(student, everything())
     
    if (grepl(course_code, files[i])) {
      cat(i, ":", files[i], "; ") 
      } else { 
        cat("\n----------> ", i, ": wrong file! - ", files[i], "\n")
        file.copy(file.path(pdf_path, script_dir, files[i]), file.path(pdf_path, "wrongScripts", files[i]), 
                   overwrite = TRUE)
        }
  
    df.MC <- bind_rows(df.MC, answers_wide)
    
    } #end of else
  
  } #end of for-loop

```

# Sanity checks
```{r}

(df.MC %>% filter(type == "Answer"))$count %>% unique()
(df.MC %>% filter(type == "Correct"))$count %>% unique()

df.Answer <- df.MC %>% filter(type == "Answer") %>% 
  select(-type) %>% 
  rename_at(vars(starts_with("Question_")), 
            list(~ str_replace(., "Question_", "a")))

df.Correct <- df.MC %>% filter(type == "Correct") %>%   
  select(-type) %>% 
  rename_at(vars(starts_with("Question_")), 
            list(~ str_replace(., "Question_", "Cor")))



df.merged <- left_join(df.Answer, df.Correct, 
                       by = "student",
                       suffix = c("Ans", "Cor")
                       ) %>% 
  select(student, countCor, starts_with("a"), everything()) %>% 
  arrange(countCor) 

xlsx::write.xlsx(df.merged, file = paste0("G:/My Drive/! ! ! Download/", course_code, "_MCmarks.xlsx"),
                 append = FALSE)

# randomly select 4 cases below "15 correct" for checking
df.check <- df.merged %>% 
  filter(countCor <= 15) %>% 
  mutate(key = paste0(student, "_", countCor)) %>% 
  select(key, starts_with("a")) %>% 
  sample_n(4) %>% 
  t()

```

# Write back LQ and MCQ marks to exam scripts
```{r}

destin_dir = "markedScripts"  
script_dir = "allScripts"  
pdf_path = "D:\\OneDrive - City, University of London\\@Courses\\FR2203\\! Xchg"
files <- list.files(path = file.path(pdf_path, script_dir))
#keep only pdf files
files <- files[grepl(".pdf", files)]



df.MC <- data.frame()
#loop through all pdf files
for(i in 1:min(1, length(files))){  #length(files)
  
#i=1
  pdf_file <- file.path(pdf_path, script_dir, files[i])
  
  
  studentID <- (files[i] %>% stringr::str_split(pattern = "( |\\p{P})", n = 2, simplify = T) %>% 
                     c())[1]  
    
  data_prelim <- data.frame()
  for (j in ifelse(studentID == "180003772" | studentID == "180026374", 3, 2):3) {  

#j=2    
    data_temp <- pdftools::pdf_data(pdf_file)[[j]]  
      
    # pdf_file <- file.path(pdf_path, script_dir, "180003772.FR2203.pdf")
    # data_prelim <- pdftools::pdf_data(pdf_file)[[3]] %>% 
      

mark_MCQ = 45
mark_Q21 = 22
mark_Q22 = 17
mark_Total = 84
    
# a = paste0("Starting portfolio value: $", prettyNum(1000000,big.mark=",",scientific=F))
# b = "Inflation assumptions of 3% annually"
# c = "Average annual returns: 6%"
# d ="Average annual volatility: 7%"
MCQ = paste0("MC = ", mark_MCQ)    
Q21 = paste0("Q21 = ", mark_Q21)
Q22 = paste0("Q22 = ", mark_Q22)
divider = paste0("-------------")
Total = paste0("Total = ", mark_Total)

#pdf('out.pdf',width=5,height=5)
pdf(file.path(pdf_path, destin_dir, 'out.pdf'), 
    width=8.27, height=11.69)
plot(NA, xlim=c(0, 8.27), ylim=c(0, 11.69), bty='n',
     xaxt='n', yaxt='n', xlab='', ylab='')
# text(1,4,a, pos=4)
# text(1,3,b, pos=4)
# text(1,2,c, pos=4)
# text(1,1,d, pos=4)
text(0, 0.7, MCQ, pos = 4, col = "red")
text(0, 0.5, Q21, pos = 4, col = "red")
text(0, 0.3, Q22, pos = 4, col = "red")
text(0, 0.15, divider, pos = 4, col = "red")
text(0, 0.0, Total, pos = 4, col = "red")
#points(rep(1,4),1:4, pch=15)
dev.off()
    
    
      
      
#    if (nrow(data_prelim) == 60) break
    
    } #end of inner for-loop
  
  } #end of for-loop





library(magick)

# convert p. 1 of exam script to an image file
file_convert <- pdftools::pdf_convert(pdf_file, format = "png", pages = 1:1)  # format = "jpg"

img_src <- image_read(file.path(here::here(), file_convert))

img_out <- image_draw(frink)
text(30, 700, MCQ, pos = 4, col = "red")
text(30, 710, Q21, pos = 4, col = "red")
text(30, 720, Q22, pos = 4, col = "red")
text(30, 730, divider, pos = 4, col = "red")
text(30, 740, Total, pos = 4, col = "red")
dev.off()

# plot the image file  
image_write(img_out , format = "pdf", 
            file.path(pdf_path, destin_dir, 'out2.pdf'))

# Cleanup the image file
unlink(c(file_convert))













# Import the image
# img.file <- system.file(file.path("images", "background-image.png"),
#                        package = "ggpubr")
img <- png::readPNG(file.path(here::here(), file_convert))

library(png)
library(ggplot2)
# Plot with background image
p <- ggplot(iris, aes(Species, Sepal.Length)) +
# background_image(img) +
 geom_boxplot(aes(fill = Species), color = "white") 
#+ fill_palette("jco")

ggimage::ggbackground(p, img)


# open the pdf device to accept all the plots and texts to be printed to the device
pdf(file.path(pdf_path, destin_dir, 'out2.pdf'), 
    width=8.27, height=11.69)

# plot the image file first 
p0 <- ggplotify::as.ggplot(~
  raster::plotRGB(r, axes=FALSE, 
                margins = FALSE, plt = c(0,0,0,0))
)

# plot a null placeholder for the texts to be included next
p <- ggplotify::as.ggplot(~
plot(NA, xlim=c(0, 8.27), ylim=c(0, 11.69), bty='n',
     xaxt='n', yaxt='n', xlab='', ylab='')
) + 
  p0 + 
  annotate(geom="text", x=0.1, y=0.17, label=MCQ, color="red")

text(1, 1.7, MCQ, pos = 4, col = "red")
text(1, 1.5, Q21, pos = 4, col = "red")
text(1, 1.3, Q22, pos = 4, col = "red")
text(1, 1.15, divider, pos = 4, col = "red")
text(1, 1.0, Total, pos = 4, col = "red")

# close the pdf device
dev.off()

# Cleanup the image file
unlink(c(file_convert))








library(staplr)
options('staplr_java_options' = '-Xmx512m')

pdfFile = system.file('testForm.pdf', package = 'staplr')
output_file <- file.path(pdf_path, destin_dir, 'out.pdf')
select_pages(selpages = 1, 
             pdfFile, 
#             pdf_file, 
             "D:\\OneDrive - City, University of London\\@Courses\\FR2203\\! Xchg\\markedScripts\\out2.pdf")

pdfFile = system.file('testForm.pdf', package = 'staplr')
fields = get_fields(pdfFile)

file.path(pdf_path, destin_dir, 'out.pdf')


pdf_convert("news.pdf", pages = 1:3)





```

